# Generated by Django 5.0.6 on 2024-06-23 18:35

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField(blank=True, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d')),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('country', models.CharField(blank=True, max_length=70, null=True)),
                ('profession', models.CharField(blank=True, max_length=80, null=True)),
                ('bgpic', models.ImageField(blank=True, null=True, upload_to='bg_pics/%Y/%m/%d')),
                ('followers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='apple.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='apple.person')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='apple.person')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='apple.person')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('text', models.TextField(blank=True, max_length=1500, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.person')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.post')),
            ],
        ),
    ]
